environment:
  node_version: "4"

install:
  - ps: Install-Product node $env:node_version
  - refreshenv
  - npm i -g yarn
  - yarn global add webpack
  - yarn

test_script:
  - yarn test

build: off
